#!/usr/bin/env node
/**
 * Starts the production server on the address the operator chose at install
 * time (HOSTNAME / PORT in .env).
 *
 * `next start` alone hardcodes the port, and reading .env is not something npm
 * scripts can do portably, so this wrapper resolves both values and spawns the
 * real server as a child process. The child is forwarded the same signals, so
 * Ctrl+C and the Windows "stop" script shut everything down cleanly.
 */

import { spawn } from 'node:child_process';
import fs from 'node:fs';
import net from 'node:net';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const isWindows = process.platform === 'win32';

/** Minimal .env reader: the file is generated by scripts/setup.mjs. */
function readEnv() {
  const file = path.join(ROOT, '.env');
  if (!fs.existsSync(file)) return {};
  const out = {};
  for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
    const m = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
    if (m) out[m[1]] = m[2].replace(/^"|"$/g, '');
  }
  return out;
}

function isPortFree(host, port) {
  return new Promise((resolve) => {
    const server = net.createServer();
    server.once('error', () => resolve(false));
    server.once('listening', () => server.close(() => resolve(true)));
    server.listen(port, host === '0.0.0.0' ? undefined : host);
  });
}

const env = { ...process.env, ...readEnv() };
const hostname = env.HOSTNAME || '0.0.0.0';
const port = Number(env.PORT || 3000);

if (!Number.isInteger(port) || port < 1 || port > 65535) {
  console.error(`\u001b[31m\u2717\u001b[0m PORT invalide dans .env : ${env.PORT}`);
  process.exit(1);
}

if (!(await isPortFree(hostname, port))) {
  console.error('');
  console.error(`\u001b[31m\u001b[1m  Le port ${port} est deja utilise.\u001b[0m`);
  console.error('');
  console.error('  Arretez l\'application en cours (stop.bat, ou Ctrl+C dans son terminal),');
  console.error(`  ou changez PORT dans le fichier .env puis relancez.`);
  console.error('');
  process.exit(1);
}

console.log('');
console.log(`\u001b[32m\u2713\u001b[0m Demarrage sur http://${hostname === '0.0.0.0' ? 'localhost' : hostname}:${port}`);
if (hostname === '0.0.0.0') {
  console.log('  \u001b[2m(ecoute aussi le reseau local)\u001b[0m');
}
console.log('  \u001b[2mCtrl+C pour arreter\u001b[0m');
console.log('');

const nextBin = isWindows ? 'next.cmd' : 'next';
const child = spawn(nextBin, ['start', '-H', hostname, '-p', String(port)], {
  cwd: ROOT,
  env,
  stdio: 'inherit',
  shell: isWindows,
});

for (const signal of ['SIGINT', 'SIGTERM']) {
  process.on(signal, () => {
    if (!child.killed) child.kill(signal);
  });
}

child.on('exit', (code, signal) => {
  process.exit(signal ? 0 : (code ?? 0));
});
